In [1]:
import numpy as np
cache = (np.array([[-1.52855314,  3.32524635,  2.13994541,  2.60700654, -0.75942115],
         [-1.98043538,  4.1600994 ,  0.79051021,  1.46493512, -0.45506242]]),
  np.array([[ 0.        ,  3.32524635,  2.13994541,  2.60700654,  0.        ],
         [ 0.        ,  4.1600994 ,  0.79051021,  1.46493512,  0.        ]]),
  np.array([[-1.09989127, -0.17242821, -0.87785842],
         [ 0.04221375,  0.58281521, -1.10061918]]),
  np.array([[ 1.14472371],
         [ 0.90159072]]),
  np.array([[ 0.53035547,  5.94892323,  2.31780174,  3.16005701,  0.53035547],
         [-0.69166075, -3.47645987, -2.25194702, -2.65416996, -0.69166075],
         [-0.39675353, -4.62285846, -2.61101729, -3.22874921, -0.39675353]]),
  np.array([[ 0.53035547,  5.94892323,  2.31780174,  3.16005701,  0.53035547],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]),
  np.array([[ 0.50249434,  0.90085595],
         [-0.68372786, -0.12289023],
         [-0.93576943, -0.26788808]]),
  np.array([[ 0.53035547],
         [-0.69166075],
         [-0.39675353]]),
  np.array([[-0.3771104 , -4.10060224, -1.60539468, -2.18416951, -0.3771104 ]]),
  np.array([[ 0.40682402,  0.01629284,  0.16722898,  0.10118111,  0.40682402]]),
  np.array([[-0.6871727 , -0.84520564, -0.67124613]]),
  np.array([[-0.0126646]]))

In [3]:
print(type(cache))

<class 'tuple'>


In [4]:
print(len(cache))

12


In [5]:

for item in cache:
    print(item)

[[-1.52855314  3.32524635  2.13994541  2.60700654 -0.75942115]
 [-1.98043538  4.1600994   0.79051021  1.46493512 -0.45506242]]
[[0.         3.32524635 2.13994541 2.60700654 0.        ]
 [0.         4.1600994  0.79051021 1.46493512 0.        ]]
[[-1.09989127 -0.17242821 -0.87785842]
 [ 0.04221375  0.58281521 -1.10061918]]
[[1.14472371]
 [0.90159072]]
[[ 0.53035547  5.94892323  2.31780174  3.16005701  0.53035547]
 [-0.69166075 -3.47645987 -2.25194702 -2.65416996 -0.69166075]
 [-0.39675353 -4.62285846 -2.61101729 -3.22874921 -0.39675353]]
[[0.53035547 5.94892323 2.31780174 3.16005701 0.53035547]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]
[[ 0.50249434  0.90085595]
 [-0.68372786 -0.12289023]
 [-0.93576943 -0.26788808]]
[[ 0.53035547]
 [-0.69166075]
 [-0.39675353]]
[[-0.3771104  -4.10060224 -1.60539468 -2.18416951 -0.3771104 ]]
[[0.40682402 0.01629284 0.16722898 0.10118111 0.40682402]]
[[-0.6871727  -0.84520564 -0.671

In [6]:
print(cache[1])

[[0.         3.32524635 2.13994541 2.60700654 0.        ]
 [0.         4.1600994  0.79051021 1.46493512 0.        ]]


In [7]:
print(cache[1].shape)

(2, 5)


In [8]:
print(cache[3])

[[1.14472371]
 [0.90159072]]


In [9]:
print(cache[3].shape)

(2, 1)


In [14]:
for i in range(len(cache)):
    print(cache[i].shape)

(2, 5)
(2, 5)
(2, 3)
(2, 1)
(3, 5)
(3, 5)
(3, 2)
(3, 1)
(1, 5)
(1, 5)
(1, 3)
(1, 1)
